name: CI for wxSQLite3
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies (Linux)
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libwxgtk3.0-gtk3-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install dependencies (macOS)
      run: |
        brew update
        brew install automake
        brew install wxmac
      if: matrix.os == 'macos-latest'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: |
        autoreconf
        ./configure
    - name: Build
      run: |
        make
    - name: Testing
      run: |
        ./samples/minimal -t -s ./samples
    - name: Installing
      run: |
        sudo make install
