version: 2.1
jobs:
  build:
    docker:
      - image: moneymanagerex/mmex_build_env:ubuntu.bionic
    steps: 
      - run:
          command: |
            cd $HOME;
            git config --global http.sslVerify false
            git clone --recurse https://github.com/wxWidgets/wxWidgets.git
            cd wxWidgets-3.2.0;
            git checkout tags/v3.2.0
            mkdir build-linux;
            cd build-linux;
            ../configure --disable-shared --enable-cxx11 --with-cxx=11 --enable-webview --with-gtk=3 --enable-unicode --enable-intl;
            make;