version: 2.1
jobs:
  build:
    machine: true
    steps: 
      - checkout
      - run: docker run --rm  \
                    -v $HOME/.ccache:/root/.ccache \
                    -v $HOME:/moneymanagerex 
                    moneymanagerex/mmex_build_env:ubuntu.bionic \
                    bash -c "cmake && cmake --build . --target package && eval \$MMEX_INST_CMD"
