version: 2.1
jobs:
  build:
    machine: true
    steps: 
      - checkout
      - run: docker run -it --rm -w /moneymanagerex/build -e -j4 \
                    -v $HOME/.ccache:/root/.ccache \
                    -v $TRAVIS_BUILD_DIR:/moneymanagerex moneymanagerex/mmex_build_env:ubuntu.bionic \
                    bash -c "cmake && cmake --build . --target package && eval \$MMEX_INST_CMD"
