version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps: 
      - run:
          command: |
            cd $HOME;
            curl -fsSL -O https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.0/wxWidgets-3.2.0.tar.bz2;
            tar xzf wxWidgets-*.tar.bz2;
            cd wxWidgets-3.2.0;
            mkdir build-linux;ß
            cd build-linux;
            ../configure --disable-shared --enable-cxx11 --with-cxx=11 --enable-webview --with-gtk=3 --enable-unicode --enable-intl;
            make;