version: 2.1
jobs:
  build:
    docker:
      image: moneymanagerex/mmex_build_env:ubuntu.bionic
      steps: 
        run: cd src/db
        run: python ../../util/sqlite2cpp.py ../../database/tables_v1.sql && rm -f sql*.sql *.mmdbg
        run: python ../../util/sqliteupgrade2cpp.py ../../database
        run: cd ../.. && mkdir build && cd build
   